apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tf2.fullname" . }}
  labels:
    {{- include "tf2.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tf2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tf2.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "tf2.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SRCDS_TOKEN
              value: {{ .Values.tf2.serverToken }}
            - name: SRCDS_RCONPW
              value: {{ .Values.tf2.rconPassword }}
            - name: SRCDS_MAXPLAYERS
              value: "{{ .Values.tf2.maxPlayers }}"
          ports:
            - name: tf2 
              containerPort: 27015 
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
