apiVersion: v1
kind: Service
metadata:
  name: {{ include "tf2.fullname" . }}
  labels:
    {{- include "tf2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 27015 
      protocol: TCP
      name: tf2
  selector:
    {{- include "tf2.selectorLabels" . | nindent 4 }}
